export const data = [
  {
    title: "Rick and Morty",
    url: "https://rick-and-morty-529c1.web.app/",
    summary: "",
    img: "rick.png",
    tech: ["ReactJs"],
  },
  {
    title: "Pelis",
    url: "https://pelis-psi.vercel.app/",
    summary: "",
    img: "pelis.png",
    tech: ["ReactJs"],
  },
  {
    title: "Rock Paper Scissors",
    url: "https://rock-paper-and-scissors-a5e38.web.app/",
    summary: "",
    img: "rock-paper-scissors.png",
    tech: ["ReactJs"],
  },
  {
    title: "Pokedex",
    url: "https://pokedex-ashen-two.vercel.app/",
    summary: "",
    img: "pokedex.png",
    tech: ["ReactJs"],
  },
  {
    title: "Wordle",
    url: "https://wordle-df8a4.web.app",
    summary: "",
    img: "wordle.png",
    tech: ["ReactJs"],
  },
  {
    title: "Cryptoverse",
    url: "https://cryptoverse-16bb2.web.app",
    summary: "",
    img: "cryptoverse.png",
    tech: ["ReactJs"],
  },
  // {
  //   title: 'Meeti',
  //   url: 'https://evening-peak-26151.herokuapp.com/',
  //   summary: '',
  //   img: 'meeti.jpg',
  //   tech: ['NodeJs', 'MongoDB'],
  //   classCustom: 'card-a',
  // },
  // {
  //   title: 'Dev Jobs',
  //   url: 'https://devjobs-yoneikerappnode.herokuapp.com',
  //   summary: '',
  //   img: 'devjobs.jpg',
  //   tech: ['NodeJs', 'MongoDB'],
  // },
  // {
  //   title: 'Up Task Project',
  //   url: 'https://uptaskproject-yoneikerappnode.herokuapp.com',
  //   summary: '',
  //   img: 'uptask.jpg',
  //   tech: ['NodeJs', 'MySQL'],
  // },
  // {
  //   title: 'Img Share',
  //   url: 'https://imgshare-yoneikerappnode.herokuapp.com',
  //   summary: '',
  //   img: 'imgshare.jpg',
  //   tech: ['NodeJs', 'MongoDB'],
  // },
  {
    title: "CorporateV2",
    url: "https://yone27.github.io/MisTemplates/corporatev2/",
    summary: "",
    img: "works1.jpg",
    tech: ["Templates"],
    classCustom: "card-a",
  },
  {
    title: "Studio Tattoo",
    url: "https://yone27.github.io/MisTemplates/studioTattoo",
    summary: "",
    img: "works2.jpg",
    tech: ["Templates"],
    classCustom: "card-a",
  },
  {
    title: "Creative Agency",
    url: "https://yone27.github.io/MisTemplates/creativeAgency",
    summary: "",
    img: "works10.jpg",
    tech: ["Templates"],
    classCustom: "card-a",
  },
  {
    title: "Fitness",
    url: "https://yone27.github.io/MisTemplates/couching",
    summary: "",
    img: "works11.jpg",
    tech: ["Templates"],
    classCustom: "card-a",
  },
  {
    title: "Relocation",
    url: "https://yone27.github.io/MisTemplates/relocation",
    summary: "",
    img: "works9.jpg",
    tech: ["Templates"],
    classCustom: "card-a",
  },
  {
    title: "LawFirm",
    url: "https://yone27.github.io/MisTemplates/lawFirm",
    summary: "",
    img: "works13.jpg",
    tech: ["Templates"],
    classCustom: "card-a",
  },
  {
    title: "Dentist",
    url: "https://yone27.github.io/MisTemplates/dentist",
    summary: "",
    img: "works12.jpg",
    tech: ["Templates"],
    classCustom: "card-a",
  },
  {
    title: "Sim Mobile",
    url: "https://yone27.github.io/MisTemplates/simMobile",
    summary: "",
    img: "works14.jpg",
    tech: ["Templates"],
    classCustom: "card-a",
  },
];

export default data;
